name = "plonky3-example"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CertiPlonk"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
# weak.linter.mathlibStandardSet = true
# maxSynthPendingDepth = 3
# linter.hashCommand = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.23.0-rc2"

[[require]]
name = "LeanZKCircuit"
git = "https://github.com/NethermindEth/leanzkcircuit.git"
rev = "Dom/plonky3"

[[lean_lib]]
name = "CertiPlonk"
